eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/924723498/configServer.git
          searchPaths: /
  application:
    name: config-server

#http://localhost:8888/config-client-dev.properties
#http://localhost:8888/configx/configddd 可以访问到文件